[build]
builder = "RAILPACK"
buildCommand = "uv sync --no-dev --locked"

[deploy]
startCommand = "uv run pogodapp"
healthcheckPath = "/health"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
